interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
}

interface McpToolExport {
  tools: McpToolDefinition[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<unknown>;
  meter?: { credits: number };
  cost?: Record<string, unknown>;
  provider?: string;
}

/**
 * AI Feeds MCP.
 *
 * Artificial intelligence — research labs, industry news and expert newsletters.
 * CF-robust RSS / Atom / RDF reader over a curated, edge-verified registry; on a
 * Cloudflare egress block it falls back to the rss2json proxy. (Generated by
 * scripts/gen-feeds-packs.mjs from scripts/feeds-registry.mjs — do not hand-edit.)
 */


const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const PROXY = 'https://api.rss2json.com/v1/api.json';
const MAX_ITEMS = 50;

interface FeedDef { title: string; url: string; category: string; source: string; description: string }

const FEEDS: Record<string, FeedDef> = {
  openai: { title: "OpenAI Blog", url: "https://openai.com/blog/rss.xml", category: "ai", source: "openai.com", description: "OpenAI research & product announcements" },
  deepmind: { title: "Google DeepMind Blog", url: "https://deepmind.google/blog/rss.xml", category: "ai", source: "deepmind.google", description: "DeepMind AI research" },
  'google-ai': { title: "Google AI Blog", url: "https://blog.google/technology/ai/rss/", category: "ai", source: "blog.google", description: "Google AI announcements" },
  huggingface: { title: "Hugging Face Blog", url: "https://huggingface.co/blog/feed.xml", category: "ai", source: "huggingface.co", description: "Open-source ML / AI articles" },
  'nvidia-blog': { title: "NVIDIA Blog", url: "https://blogs.nvidia.com/feed/", category: "ai", source: "blogs.nvidia.com", description: "NVIDIA AI & accelerated-computing news" },
  bair: { title: "Berkeley AI Research", url: "https://bair.berkeley.edu/blog/feed.xml", category: "ai", source: "bair.berkeley.edu", description: "BAIR AI-research blog" },
  'microsoft-research': { title: "Microsoft Research", url: "https://www.microsoft.com/en-us/research/feed/", category: "ai", source: "microsoft.com", description: "Microsoft Research (AI & computing)" },
  'the-gradient': { title: "The Gradient", url: "https://thegradient.pub/rss/", category: "ai", source: "thegradient.pub", description: "AI/ML research perspectives" },
  bdtechtalks: { title: "TechTalks", url: "https://bdtechtalks.com/feed/", category: "ai", source: "bdtechtalks.com", description: "AI/ML explained for business & tech" },
  'one-useful-thing': { title: "One Useful Thing", url: "https://www.oneusefulthing.org/feed", category: "ai", source: "oneusefulthing.org", description: "Practical AI essays (Ethan Mollick)" },
  'simon-willison': { title: "Simon Willison", url: "https://simonwillison.net/atom/everything/", category: "ai", source: "simonwillison.net", description: "LLMs, tools & software engineering" },
  'last-week-in-ai': { title: "Last Week in AI", url: "https://lastweekin.ai/feed", category: "ai", source: "lastweekin.ai", description: "Weekly AI news roundup" },
  'import-ai': { title: "Import AI", url: "https://importai.substack.com/feed", category: "ai", source: "importai.substack.com", description: "Weekly AI research & policy (Jack Clark)" },
  interconnects: { title: "Interconnects", url: "https://www.interconnects.ai/feed", category: "ai", source: "interconnects.ai", description: "AI/ML research analysis (Nathan Lambert)" },
  'gary-marcus': { title: "Gary Marcus", url: "https://garymarcus.substack.com/feed", category: "ai", source: "garymarcus.substack.com", description: "AI critique & analysis" },
  'sebastian-raschka': { title: "Ahead of AI", url: "https://magazine.sebastianraschka.com/feed", category: "ai", source: "magazine.sebastianraschka.com", description: "ML & LLM deep dives" },
  'ai-supremacy': { title: "AI Supremacy", url: "https://www.ai-supremacy.com/feed", category: "ai", source: "ai-supremacy.com", description: "AI-industry analysis" },
  'arxiv-cs-ai': { title: "arXiv cs.AI", url: "https://rss.arxiv.org/rss/cs.AI", category: "ai", source: "arxiv.org", description: "arXiv Artificial Intelligence preprints (cs.AI)" },
  'arxiv-cs-lg': { title: "arXiv cs.LG", url: "https://rss.arxiv.org/rss/cs.LG", category: "ai", source: "arxiv.org", description: "arXiv Machine Learning preprints (cs.LG)" },
  'arxiv-cs-cl': { title: "arXiv cs.CL", url: "https://rss.arxiv.org/rss/cs.CL", category: "ai", source: "arxiv.org", description: "arXiv Computation & Language / NLP preprints (cs.CL)" },
  'arxiv-cs-cv': { title: "arXiv cs.CV", url: "https://rss.arxiv.org/rss/cs.CV", category: "ai", source: "arxiv.org", description: "arXiv Computer Vision & Pattern Recognition preprints (cs.CV)" },
  'arxiv-stat-ml': { title: "arXiv stat.ML", url: "https://rss.arxiv.org/rss/stat.ML", category: "ai", source: "arxiv.org", description: "arXiv Machine Learning (statistics) preprints (stat.ML)" },
};

const tools: McpToolExport['tools'] = [
  {
    name: 'list_feeds',
    description: 'List the curated artificial-intelligence feeds (id, title, category, source). Optionally filter by category (ai) or keyword. Pass an id to read_feed.',
    inputSchema: {
      type: 'object',
      properties: {
        category: { type: 'string', description: 'Filter by category: ai.' },
        query: { type: 'string', description: 'Keyword to match in feed title/source/description.' },
      },
    },
  },
  {
    name: 'read_feed',
    description: 'Read a curated artificial-intelligence feed by its id (from list_feeds). Returns normalized items (title, link, published, summary). Optionally filter items by keyword.',
    inputSchema: {
      type: 'object',
      properties: {
        feed: { type: 'string', description: 'Curated feed id (from list_feeds).' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['feed'],
    },
  },
  {
    name: 'fetch_feed',
    description: 'Fetch and normalize any RSS / Atom / RDF feed by URL. CF-robust: fetches directly and falls back to a proxy if the source blocks the gateway. Use list_feeds first for curated sources.',
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Feed URL, e.g. "https://news.ycombinator.com/rss".' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['url'],
    },
  },
];

async function callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
  switch (name) {
    case 'list_feeds':
      return listFeeds(args);
    case 'read_feed': {
      const id = String(args.feed ?? '').trim();
      const def = FEEDS[id];
      if (!def) throw new Error(`Unknown feed "${args.feed}". Use list_feeds to see valid ids.`);
      return readFeed(def.url, args, { id, ...def });
    }
    case 'fetch_feed': {
      const url = String(args.url ?? '').trim();
      if (!/^https?:\/\//i.test(url)) throw new Error('Pass a valid feed `url` (http/https).');
      return readFeed(url, args);
    }
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

function listFeeds(args: Record<string, unknown>): unknown {
  const cat = typeof args.category === 'string' ? args.category.trim().toLowerCase() : '';
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const feeds = Object.entries(FEEDS)
    .filter(([, d]) => (!cat || d.category === cat) && (!q || `${d.title} ${d.source} ${d.description}`.toLowerCase().includes(q)))
    .map(([id, d]) => ({ id, title: d.title, category: d.category, source: d.source, description: d.description }));
  return { categories: [...new Set(Object.values(FEEDS).map((d) => d.category))].sort(), count: feeds.length, feeds };
}

async function readFeed(url: string, args: Record<string, unknown>, meta?: Record<string, unknown>): Promise<unknown> {
  const limit = clamp(numArg(args.limit, 20), 1, MAX_ITEMS);
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const { items, via } = await getFeed(url);
  let out = items;
  if (q) out = out.filter((i) => `${i.title} ${i.summary}`.toLowerCase().includes(q));
  return {
    feed: meta ? { id: meta.id, title: meta.title, source: meta.source } : { url },
    via,
    total_matching: out.length,
    count: Math.min(out.length, limit),
    items: out.slice(0, limit),
  };
}

interface FeedItem { title: string; link: string; published?: string; summary?: string; author?: string; categories?: string[]; id?: string }

async function getFeed(url: string): Promise<{ items: FeedItem[]; via: string }> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/rss+xml, application/atom+xml, application/xml, text/xml, */*' } });
    if (res.ok) {
      const xml = await res.text();
      if (/<(item|entry)[\s>]/i.test(xml)) return { items: parseFeed(xml), via: 'direct' };
    }
  } catch {
    /* fall through to proxy */
  }
  const pres = await fetch(`${PROXY}?rss_url=${encodeURIComponent(url)}&count=${MAX_ITEMS}`, { headers: { 'User-Agent': UA, Accept: 'application/json' } });
  const body = (await pres.json().catch(() => ({}))) as { status?: string; items?: ProxyItem[] };
  if (body.status === 'ok' && Array.isArray(body.items)) {
    return {
      items: body.items.map((i) => ({
        title: clean(i.title), link: i.link || '', published: i.pubDate || undefined,
        summary: clean(i.description)?.slice(0, 500) || undefined, author: i.author || undefined,
        categories: Array.isArray(i.categories) ? i.categories : undefined, id: i.guid || i.link,
      })),
      via: 'proxy',
    };
  }
  throw new Error(`Feed unreachable: ${url} (blocked directly and via proxy). The source may block datacenter egress.`);
}

interface ProxyItem { title?: string; link?: string; pubDate?: string; description?: string; author?: string; categories?: string[]; guid?: string }

function parseFeed(xml: string): FeedItem[] {
  const out: FeedItem[] = [];
  const blocks = xml.match(/<(item|entry)[\s>][\s\S]*?<\/\1>/gi) ?? [];
  for (const b of blocks) {
    const link = extractLink(b);
    out.push({
      title: clean(tag(b, 'title')),
      link,
      published: tag(b, 'pubDate') || tag(b, 'published') || tag(b, 'updated') || tag(b, 'dc:date') || undefined,
      summary: clean(tag(b, 'description') || tag(b, 'summary') || tag(b, 'content:encoded') || tag(b, 'content'))?.slice(0, 500) || undefined,
      author: clean(tag(b, 'dc:creator') || authorName(b)) || undefined,
      categories: cats(b),
      id: tag(b, 'guid') || tag(b, 'id') || link,
    });
  }
  return out;
}

function extractLink(b: string): string {
  const rss = b.match(/<link>([\s\S]*?)<\/link>/i);
  if (rss && rss[1].trim()) return clean(rss[1]);
  const alt = b.match(/<link[^>]*rel=["']alternate["'][^>]*href=["']([^"']+)["']/i) || b.match(/<link[^>]*href=["']([^"']+)["']/i);
  return alt ? alt[1].trim() : '';
}
function authorName(b: string): string {
  const a = b.match(/<author>([\s\S]*?)<\/author>/i);
  if (!a) return '';
  const name = a[1].match(/<name>([\s\S]*?)<\/name>/i);
  return name ? name[1] : a[1];
}
function cats(b: string): string[] | undefined {
  const list: string[] = [];
  for (const m of b.matchAll(/<category[^>]*?(?:term=["']([^"']+)["'][^>]*)?>([\s\S]*?)<\/category>/gi)) {
    const v = clean(m[1] || m[2]);
    if (v) list.push(v);
  }
  for (const m of b.matchAll(/<category[^>]*term=["']([^"']+)["'][^>]*\/>/gi)) list.push(m[1]);
  return list.length ? [...new Set(list)].slice(0, 10) : undefined;
}
function tag(xml: string, name: string): string {
  const m = xml.match(new RegExp(`<${name.replace(':', '\\:')}[^>]*>([\\s\\S]*?)<\\/${name.replace(':', '\\:')}>`, 'i'));
  return m ? unwrap(m[1]) : '';
}
function unwrap(s: string): string {
  const m = s.trim().match(/^<!\[CDATA\[([\s\S]*?)\]\]>$/);
  return (m ? m[1] : s).trim();
}
function clean(s: unknown): string {
  if (typeof s !== 'string') return '';
  return s
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/<\/?[a-zA-Z][^>]*>/g, ' ')
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ').trim();
}
function numArg(v: unknown, dflt: number): number {
  const n = typeof v === 'number' ? v : typeof v === 'string' ? Number(v) : NaN;
  return Number.isFinite(n) ? n : dflt;
}
function clamp(n: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, Math.trunc(n)));
}

export default { tools, callTool, meter: { credits: 1 } } satisfies McpToolExport;
